### ISSUE TITLE
Fatal error on API

### ISSUE THREAD

**Issue by atm-greg** [OPEN-DSI/dolibarr_module_advancedictionaries#5]
Since Dolibarr V11, there is a modification on DolibarrApi class that create a fatal error on API with this module.
The $db variable was declared as "static protected $db" before Dolibarr V11 and just "protected $db" since then.

To insure compatibility, we recommend to create a branch for Compatibility with Dolibarr < V11 and another for Dolibarr > V10.5

Best regards

**Comment by eldk** [comment]
Hello,

Got the same with Dolibarr 14.05 and dolibarr_module_advancedictionaries 4.0.27.

```
PHP Fatal error:  Cannot redeclare non static DolibarrApi::$db as static AdvanceDictionariesApi::$db in /home/domain.tld/public_html/dolibarr/custom/advancedictionaries/class/api_advancedictionariesapi.class.php on line 0, referer: domain.tld/api/index.php/explorer
```

How should I help ?

Thanks,

Eric

**Comment by aspangaro** [comment]
Solve on new version
